version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=ybooking
      - POSTGRES_PASSWORD=ybooking
      - POSTGRES_DB=ybooking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build: .
    command: celery worker -A ybooking -l INFO
    volumes:
      - .:/code
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data: