# Generated by Django 3.2.5 on 2021-08-05 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Patronymic (optional)')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Is doctor')),
                ('sex', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Undefined')], default=3, verbose_name='Sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Vacation start date')),
                ('stop_date', models.DateField(verbose_name='Vacation stop date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybooking_app.profile', verbose_name='Doctor')),
            ],
            options={
                'db_table': 'vacation',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Session start datetime')),
                ('stop', models.DateTimeField(verbose_name='Session stop datetime')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='ybooking_app.profile', verbose_name='Doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ybooking_app.profile', verbose_name='Client')),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_days', models.IntegerField(default=7, verbose_name='Days number to generate sessions')),
                ('session_duration', models.IntegerField(verbose_name='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybooking_app.profile', verbose_name='Doctor')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='DayInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Interval start time')),
                ('stop_time', models.TimeField(verbose_name='Interval stop time')),
                ('weekday', models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sun'), (7, 'Sat')], default=1, verbose_name='Day of week')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ybooking_app.profile', verbose_name='Doctor')),
            ],
            options={
                'db_table': 'interval',
            },
        ),
    ]
